version: '3.8'

services:
  laravel-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=mysql
      - MYSQL_TEMPLATE_HOST=mysql
      - MYSQL_EXEC_HOST=mysql
      - JUDGE0_API_URL=http://judge0-server:2358
    depends_on:
      - mysql
      - judge0-server

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=mysql_judge0_demo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  judge0-server:
    image: judge0/judge0:1.13.0
    volumes:
      - ./judge0/judge0.conf:/judge0.conf:ro
      - ./judge0/mysql-executor.sh:/usr/local/bin/mysql-executor.sh:ro
    ports:
      - "2358:2358"
    privileged: true
    environment:
      - REDIS_URL=redis://judge0-redis:6379
      - POSTGRES_HOST=judge0-db
      - POSTGRES_DB=judge0
      - POSTGRES_USER=judge0
      - POSTGRES_PASSWORD=judge0_password
      - MYSQL_HOST=mysql
      - MYSQL_ROOT_PASSWORD=root_password
    depends_on:
      - judge0-db
      - judge0-redis
      - mysql

  judge0-db:
    image: postgres:13
    environment:
      - POSTGRES_DB=judge0
      - POSTGRES_USER=judge0
      - POSTGRES_PASSWORD=judge0_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  judge0-redis:
    image: redis:6
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  postgres_data:
  redis_data: